### PR TITLE
TF NCHW->NHWC

### PR DESCRIPTION
**Pull request by Observerspy**
conv2d in Tensorflow now only support data_format='channels_last', so just change "channels_first" to "channels_last" and add tf.transpose(self.input_states, [0, 2, 3, 1]) for input placeholder.

### CODE REVIEW

**Comment by junxiaosong** [comment]
I checked the API doc of Tensorflow 1.8 and it seems that the 'channels_first' data_format is still supported.

**Comment by Observerspy** [comment]
I just update my tf to 1.8.0 and data_format="channels_first" still got Error **"UnimplementedError (see above for traceback):  Generic conv implementation only supports NHWC tensor format for now."**

**Comment by junxiaosong** [comment]
Hi @dshnightmare，what is the version of TF you are using？Have you ever met the Error？This pull request is somehow reverting the last one #29

**Comment by junxiaosong** [comment]
I just tried both TF 1.5 and 1.8, and the original code, i.e., data_format="channels_first", works fine for both versions.

**Comment by Observerspy** [comment]
It's weird! I tried again on **win+py3.5+tf1.8** and **ubuntu+py3.6+tf1.5** both got the same error.

**Comment by junxiaosong** [comment]
I just tried for some versions of tensorflow and got the same Error as you. Thank you for the pull request. I will merge it now.

**Comment by dshnightmare** [comment]
@Observerspy @junxiaosong unimplementedError is encountered when use cpu version of tensorflow, and I think a transpose operation is better general approach for both of cpu and gpu version. It is my fault not making it clear.

**Pull request merged**
